You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

class Solution(object):
    def findTheDifference(self, s, t):
        ss=Counter(s)
        tt=Counter(t)
        for char, count in tt.items():
            if ss[char] != count:
                return char
